@startuml
class Jugador
class Eri {
+ Recoger (Item)
+ Disparar ()
- Vida vida1
- Vida vida2
}
class Fio {
+ Recoger (Item)
+ Disparar()
- Vida vida1
- Vida vida2
}
class Vida
class Moneda
class Posion
class Botiquin
class Item
class Personaje
class Caja
class CajaF
class CajaS
class CajaR
class CajaH 
class CajaL 
class CajaC 
class CajaI 
class CajaD 
class CajaG 
class Caja2H 
class CajaZ 
class CajaT 
class CajaB 
class Bomba
class ThunderCloud
class Roca 
class Granada
class FireBomb
class Misiles 
class Dron 
class Montura 
class Tanque
class Androide 
class Camello 
class Avion 
class Submarino
class Vehiculo
class Elefante 
class Taladro 
class Prisionero 
class Comida 
class Medalla
class Tanquegasolina
class CajaMunicion 
Jugador 0-- Personaje
Eri --|> Personaje
Eri "1" *-- "2" Vida
Eri "1" o-- "1..*" Moneda
Eri o-- Posion
Eri o-- Botiquin
Eri o-- Caja
Eri "1" o-- "1..2" ThunderCloud
Eri "1" o-- "1..5" Roca 
Eri "1" o-- "1..3" Granada
Eri "1" o-- "1..3" FireBomb
Eri "1" o-- "1..4" Misiles 
Eri o-- Vehiculo
Eri "1" o-- "1..3" Tanquegasolina 
Eri "1" o-- "1..*"  Prisionero 
Eri "1" o-- "1..*"  Comida 
Eri "1" o-- "1..*"  Medalla
Fio --|> Personaje
Fio "1" *-- "2" Vida
Fio "1" o-- "1..*" Moneda
Fio o-- Posion
Fio o-- Botiquin
Fio o-- Caja
Fio "1" o-- "1..2" ThunderCloud
Fio "1" o-- "1..5" Roca 
Fio "1" o-- "1..3" Granada
Fio "1" o-- "1..3" FireBomb
Fio "1" o-- "1..4" Misiles 
Fio o-- Vehiculo
Fio "1" o-- "1..3" Tanquegasolina
Fio "1" o-- "1..*"  Prisionero 
Fio "1" o-- "1..*"  Comida 
Fio "1" o-- "1..*"  Medalla
Moneda --|> Item
Posion --|> Item
Botiquin --|> Item
Caja --|> Item
CajaF --|> Caja
CajaS --|> Caja
CajaR --|> Caja
CajaH --|> Caja
CajaL --|> Caja
CajaC --|> Caja
CajaI --|> Caja
CajaD --|> Caja
CajaG --|> Caja
Caja2H --|> Caja
CajaZ --|> Caja
CajaT --|> Caja
CajaB --|> Caja
Bomba --|> Item
ThunderCloud --|> Bomba
Roca --|> Bomba
Granada --|> Bomba
FireBomb --|> Bomba
Misiles --|> Bomba
Dron --|> Vehiculo
Montura --|> Vehiculo
Tanque --|> Vehiculo
Androide --|> Vehiculo
Camello --|> Vehiculo
Avion --|> Vehiculo
Submarino --|> Vehiculo
Vehiculo --|> Item
Elefante --|> Vehiculo
Taladro --|> Vehiculo
Prisionero --|> Item
Comida --|> Item
Medalla --|> Item
Tanquegasolina --|> Item
CajaMunicion --|> Caja
@enduml
